
pipeline_config_id: data_config

data_format: pkl
train_dir: ./data/earthquake/kept/train.pkl
valid_dir: ./data/earthquake/kept/dev.pkl
test_dir: ./data/earthquake/kept/test.pkl
data_specs:
  num_event_types: 7
  pad_token_id: 7
  padding_side: right
